apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    
spec:
  tls:
    - hosts:
      - photogurus.de
      - www.photogurus.de
  ingressClassName: nginx    
  rules:
    - host: photogurus.de
      http:
        paths: 
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-cip-srv
                port:
                  number: 3000
          - path: /api/albums/?(.*)
            pathType: Prefix
            backend:
              service:
                name: album-cip-srv
                port:
                  number: 3000      
          - path: /api/images/?(.*)
            pathType: Prefix
            backend:
              service:
                name: image-cip-srv
                port:
                  number: 3000           
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cip-srv
                port:
                  number: 3000 
