name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Configure  AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2    
      - uses: tale/kubectl-action@v1
        with:
           base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl apply -f infra/k8s
      
#